# Site settings
title: Nuwan Jayawardene
email: nsgaj12@gmail.com
description: This is <strong>Ethereal</strong>, a free site template by AJ for <a href="https://html5up.net">HTML5 UP</a>. It’s fully responsive, built on HTML5 and CSS3, and released entirely for free under the Creative Commons license. Hope you dig it :)
baseurl: /website # the subpath of your site, e.g. /blog
url: https://n-jay.gitlab.io # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Build settings
markdown: kramdown

sass:
  style: compressed

incremental: true